node {
  def project = 'gs-spring-boot-docker'
  def dockerhubuser = 'bash2docker'
  def imageTag = "${dockerhubuser}/${project}:${env.BUILD_NUMBER}"

  stage('Image Creation') { // for display purposes
     // Get some code from a GitHub repository
     git 'https://github.com/CLdevops/gs-spring-boot-docker.git'
     sh "echo ${project}"
     sh "echo ${dockerhubuser}"
     sh "echo ${imageTag}"
	 // Run the maven build
	 
	 if (isUnix()) {
        sh "cd complete && ./mvnw install dockerfile:build"
		
     }
	 withDockerRegistry([ credentialsId: "9fef79f3-8d14-44ff-afa9-eae7afa9e3c9", url: "" ]) {
         sh "echo ${imageTag}"
         sh "docker tag springio/gs-spring-boot-docker:latest ${imageTag}"
         sh "docker push ${imageTag}"
     }
  }
   
  }
