node {
  def project = 'gs-spring-boot-docker'
  def dockerhubuser = 'bash2docker'
  def imageTag = "${dockerhubuser}/${project}:${env.BUILD_NUMBER}"

  stage('Image Creation') { // for display purposes
     // Get some code from a GitHub repository
     git 'https://github.com/CLdevops/gs-spring-boot-docker.git'
     sh "echo ${project}"
     sh "echo ${dockerhubuser}"
     sh "echo ${imageTag}"
	 // Run the maven build
	 
	 if (isUnix()) {
        sh "cd complete && ./mvnw install dockerfile:build"
		
     }
	 withDockerRegistry([ credentialsId: "0a7b502f-1a42-49cc-8847-149733eaa5b0", url: "" ]) {
         sh "echo ${imageTag}"
         sh "docker tag springio/gs-spring-boot-docker:latest ${imageTag}"
         sh "docker push ${imageTag}"
     }
  }
   
  }
